apiVersion: v1
kind: Service
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-crm-crm-api
  name: crm-api
  namespace: crm
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-crm-crm-api
  sessionAffinity: None
  type: ClusterIP
