apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-crm-crm-api
  name: crm-api
  namespace: crm
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-crm-crm-api
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-crm-crm-api
      namespace: crm
    spec:
     
      containers:
      - envFrom:
        - configMapRef:
            name: crm-setup
        image: agdiascloud/crm:v0
        imagePullPolicy: Always
        name: crm
      
